### ISSUE TITLE
Issue with manual sorting in the roadmap

### ISSUE THREAD

**Issue by 1tomaszwrobel** [clearflask/clearflask#150]
As a roadmap manager, I'd like to sort entries in my roadmap so I can set and see work sequence and priorities. Manual sorting works in "Now" column, however in "Later" or "Next" my changes do not save and entries are sorted in a random order.
![image](https://github.com/clearflask/clearflask/assets/95363812/a536a032-bdc3-4a21-8cf5-086e9f4b5954)

---

I use ClearFlask on:

- [x] Self-hosted (Own domain)
- [ ] Cloud (clearflask.com)
- [ ] Haven't tried (yet)

My financial contributions to ClearFlask:

- [x] I use a free Plan
- [ ] Thinking about it
- [ ] Monthly / Yearly Plan
- [ ] Lifetime Plan

**Comment by matusfaro** [comment]
I was able to reproduce it. I wrote a fix [here](https://github.com/clearflask/clearflask/commit/f7345ad6c4ac6a47a4b0fe69e76ae602d3b0fbfe). I will close this ticket once I verify the fix is working. It should make it to release 1.7.4 in a couple of days.

**Comment by matusfaro** [comment]
There is a caveat: you need to manually re-order the items to fix the issue. Sorry for the inconvenience.
